# POST http://localhost:3000/signup 
# Content-Type: application/json

# {
#     "fullname": "Shriraj",
#     "email": "patil.shriraj2914@gmail.com",
#     "password": "Shriraj29"
# }

# POST http://localhost:3000/signin
# Content-Type: application/json

# {
#     "email": "patil.shriraj2914@gmail.com",
#     "password": "Shriraj29"
# }

# GET http://localhost:3000/get-upload-url

# POST http://localhost:3000/create-blog
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZDkyOWY3MTM0MjlhNTkwNDY0OTA1OCIsImlhdCI6MTcwODczNTQ3M30.0oOhrPhbceccWjRD_GTQvEjbr21OZMfDeMOeA-QII5w

# {
#     "title": "this is a test blog",
#     "banner":  "http://example.com/image1.jpg",
#     "des": "This is the description of the blog.",
#     "content": {
#         "blocks": [ 1, 2 ]
#     },
#     "tags": [ "tag1", "tag2" ]
# }

# GET http://localhost:3000/latest-blogs

# GET http://localhost:3000/trending-blogs

# POST http://localhost:3000/search-blogs
# Content-Type: application/json

# {
#     "tag": "work"
# }

# POST http://localhost:3000/search-users
# Content-Type: application/json

# {
#     "tag": "shri"
# }

# POST http://localhost:3000/get-profile
# Content-Type: application/json

# {
#     "username": "patil.shriraj29"
# }

POST http://localhost:3000/get-blog
Content-Type: application/json

{
    "blog_id": "Don-t-Let-Google-Manage-Your-Passwordsvz-WiVhmaTsFdhY7S-96u"
}